name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - run: ./gradlew build
      - uses: ncipollo/release-action@v1
        with:
          name: Release ${{ github.ref }}
          generateReleaseNotes: true
          artifacts: "build/libs/springapp-0.0.1-SNAPSHOT-plain.jar,build/libs/springapp-0.0.1-SNAPSHOT.jar"
        